---
- name: Download package
  get_url:
    url: "https://github.com/jgraph/drawio-desktop/releases/download/v{{ drawio_version }}/{{ drawio_package_name }}-amd64-{{ drawio_version }}.deb"
    dest: "/tmp/{{ drawio_package_name }}-{{ drawio_version }}.deb"
    mode: 0644

- name: Install package
  become: true
  apt:
    deb: "/tmp/{{ drawio_package_name }}-{{ drawio_version }}.deb"
    update_cache: true
